# Generated by Django 5.1.1 on 2024-09-12 20:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(verbose_name="name")),
                ("date_start", models.DateField(verbose_name="date_start")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("готов", "Готов"),
                            ("в разработке", "В разработке"),
                        ],
                        default="в разработке",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "db_table": '"django_hw"."project"',
            },
        ),
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=app.models.get_datetime,
                        null=True,
                        validators=[app.models.check_date_created],
                        verbose_name="created",
                    ),
                ),
                ("name", models.TextField(verbose_name="name")),
                ("surname", models.TextField(verbose_name="surname")),
                ("position", models.TextField(verbose_name="position")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "developer",
                "verbose_name_plural": "developers",
                "db_table": '"django_hw"."developer"',
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=app.models.get_datetime,
                        null=True,
                        validators=[app.models.check_date_created],
                        verbose_name="created",
                    ),
                ),
                ("name", models.TextField(verbose_name="name")),
                (
                    "developers",
                    models.ManyToManyField(
                        related_name="team_developer", to="app.developer"
                    ),
                ),
            ],
            options={
                "verbose_name": "team",
                "verbose_name_plural": "teams",
                "db_table": '"django_hw"."team"',
            },
        ),
    ]
